pm2 start --name "booking1" "node index.js"
pm2 start --name "booking2" "node index.js"
pm2 start --name "booking3" "node index.js"
pm2 start --name "booking4" "node index.js"
pm2 start --name "booking5" "node index1.js"
pm2 start --name "booking6" "node index1.js"